### ISSUE TITLE
Ascension not working properly

### ISSUE THREAD

**Issue by RubenatorX** [slaymaker1907/triple-triad-ai#10]
Not sure why but, the ascension bonuses are not in effect.
Reproduce (both manual, both using MyDecks/DeckOne, ascension rule set to "Normal"):
1) Place the beastmen 4533 in the center.
2) Placing the opposing beastman card below that should not capture the card (4 vs 3+1), but it does. Also, placing a no type card with a 4 on top below it has the same effect.

**Comment by slaymaker1907** [comment]
Ascension actually doesn't seem to be working at all.

**Comment by slaymaker1907** [comment]
The issue appears to have been that the new map wasn't being used to calculate bonuses. This should be fixed now.

**Comment by slaymaker1907** [comment]
Fixed in v0.3
