### ISSUE TITLE
Cannot capture cards from the left (west)

### ISSUE THREAD

**Issue by RubenatorX** [slaymaker1907/triple-triad-ai#3]
Cannot capture cards from the left (west)
Reproduce (both players manual)
1) Place a card with a 1 on the left in any cell not in the leftmost column.
2) Place any card with not a 1 on the right to the left of the first card.
3) Be disappointed.

**Comment by RubenatorX** [comment]
CardPlayFunction.java line 116
Reads:
tryCapture(toPlay, field.getCard(row, col - 1), cardComparator, result);
Should Read:
tryCapture(toPlay, field.getCard(row, col + 1), cardComparator, result);

(Its trying to capture the card to its left twice instead of trying the card on its left and then the card on its right).

**Comment by RubenatorX** [comment]
Pull Request Submitted

**Comment by slaymaker1907** [comment]
Fixed in v0.2
