### ISSUE TITLE
Same + Combo -- Cannot Capture Cards normally

### ISSUE THREAD

**Issue by RubenatorX** [slaymaker1907/triple-triad-ai#5]
Reproduce (both players manual)
1) Place a Card
2) Try to Capture that card with another
3) Be dissapointed

**Comment by slaymaker1907** [comment]
This should now be fixed. The issue was that sameCombo was returning only the cards captured through same not including those captured through regular battle.

**Comment by slaymaker1907** [comment]
Fixed in v0.2
