### ISSUE TITLE
Ascension -- Type indicators

### ISSUE THREAD

**Issue by RubenatorX** [slaymaker1907/triple-triad-ai#6]
Should be able to see the card type of each card when ascension or decension are enabled. Difficult to  decide what to do based solely on the interface. Also, should probably show the ascension bonus on the cards on the board.

**Comment by slaymaker1907** [comment]
I've added in a way to see the card type on cards. However, I've not yet added in viewing ascension bonuses because that will require more extensive code changes.

**Comment by slaymaker1907** [comment]
Added in v0.2, the ability to see the ascension bonus for cards on the board is encapsulated in issue #9
